export const APP_SCREENS = {
  LOGIN: "LOGIN",
  SIGN_UP: "SIGN_UP",
  AUTH: "AUTH",
  AUTH_TAB: "AUTH_TAB",
  HOME: "HOME",
  CART: "CART",
  PROFILE: "PROFILE",
  CHECKOUT: "CHECKOUT",
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
};
